server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/HarDep/microservicios-1.git
          search-paths: config-data
  application:
    name: config-service
